server:
  port: 8080

spring:
  application:
    name: todo-api

  datasource:
    url: jdbc:postgresql://192.168.64.23:5432/todo_db
    username: todo_user
    password: todo_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Actuator configuration for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

logging:
  level:
    com.olixc.todo: DEBUG
    org.springframework.web: DEBUG
